# Generated by Django 3.1.6 on 2021-03-07 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='pfp',
            field=models.ImageField(default='default.jpg', upload_to=''),
        ),
    ]
