# Generated by Django 3.1.6 on 2021-03-07 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0004_auto_20210307_0252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='pfp',
            field=models.ImageField(default='default.jpg', upload_to='profile_pictures'),
        ),
    ]
