# Generated by Django 3.1.6 on 2021-03-09 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0006_auto_20210307_1926'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='commentsDate',
            new_name='commentDate',
        ),
        migrations.RenameField(
            model_name='comments',
            old_name='commentsUser',
            new_name='commentOwner',
        ),
        migrations.RenameField(
            model_name='comments',
            old_name='commentsPost',
            new_name='commentPost',
        ),
        migrations.RenameField(
            model_name='comments',
            old_name='usersComment',
            new_name='userComment',
        ),
    ]
