# Generated by Django 3.1.6 on 2021-03-09 06:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0008_auto_20210309_0107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='commentPost',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='feed.post'),
        ),
    ]
