# Generated by Django 3.1.6 on 2021-03-09 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0009_auto_20210309_0159'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='comment',
            new_name='content',
        ),
    ]
