# Generated by Django 3.1.6 on 2021-03-09 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0010_auto_20210309_0224'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='commentOwner',
            new_name='owner',
        ),
        migrations.RenameField(
            model_name='comments',
            old_name='commentPost',
            new_name='post',
        ),
    ]
