# Generated by Django 3.1.6 on 2021-03-10 02:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0012_auto_20210309_1905'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='approved_comment',
        ),
    ]
